### ISSUE TITLE
index out of bounds for length 3

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/Java-OOP#3]
index out of bounds for length 3

```
Hello World
3
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at bank.removeAccountAtPosition(bank.java:22)
	at bank.deleteAccountByAccountID(bank.java:16)
	at Main.main(Main.java:18)
```

**Comment by Aatmaj-Zephyr** [comment]
try top pointer pointing to last element instead of one more than last.

**Comment by Aatmaj-Zephyr** [comment]
Fixed
